# Базовый образ с общими системными зависимостями для dev и prod
FROM python:3.10.8-slim as python-base
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONPATH="/opt/app:$PYTHONPATH"

RUN apt-get update \
    && apt-get --no-install-recommends install -y \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./docker/wait_for_services.py /opt/

WORKDIR /opt/app
COPY requirements.txt requirements.dev.txt ./
RUN pip install -r requirements.txt -r requirements.dev.txt

COPY ./src ./src
COPY ./tests ./tests

ENTRYPOINT ["sh", "-c", "python3 /opt/wait_for_services.py \
                         && pytest ."]
