# Generated by Django 3.2 on 2023-03-16 16:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import notifications.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name', max_length=254, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Template description', null=True, verbose_name='Description')),
                ('subject', models.CharField(max_length=254, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Templates',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('users_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Recipients UUIDs. For example: 74f4c5ff-2432-4594-ae49-2f9f48f274ed, 2b2a5654-7dd3-4ea4-ae19-0d9a4a7999ba', null=True, size=None, validators=[notifications.validators.validate_uuid], verbose_name='Recipients')),
                ('transport', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'Sms'), ('websocket', 'Websocket')], max_length=50, verbose_name='Method of sending')),
                ('scheduled_time', models.DateTimeField(validators=[notifications.validators.validate_datetime], verbose_name='Time of sending')),
                ('type', models.CharField(choices=[('info', 'Info'), ('promo', 'Promo'), ('bonus', 'Bonus')], default='info', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('failed', 'Failed'), ('done', 'Done')], default='waiting', max_length=50, verbose_name='Status')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
    ]
