version: '3.7'

services:
  rabbitmq_broker:
    image: rabbitmq:3.10.6-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "8072:15672"
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 15s
      timeout: 2s
      retries: 15

  jaeger_agent:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

#TODO: Выпилить docker-compose отсюда, когда будем собирать все в один проект